### ISSUE TITLE
How do you implement this when using the Route::resource routes?

### ISSUE THREAD

**Issue by abodnar** [Propaganistas/Laravel-FakeId#1]
I'm running Laravel 5.2 and have setup my routes using the Route::resource functionality where I bind the route to a controller. However, it does not appear to be encoding the ids when getting a list of objects.

Thanks.

**Comment by Propaganistas** [comment]
Have you bound the model to the router? Be sure to use the same route parameter:

e.g.:
```php
Route::model('user', 'App\User');
Route::resource('user', 'UserController');
```
