### ISSUE TITLE
Works with Laravel 5.4?

### ISSUE THREAD

**Issue by chandank** [Propaganistas/Laravel-FakeId#12]
I followed all the steps mentioned in the readme but the ids aren't obfuscated, and still appear as integers. No errors in installation either.

1.  Ran composer, now composer.json has

``` 
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "barryvdh/laravel-debugbar": "^2.3",
        "kyslik/column-sortable": "5.4.*",
        "laracasts/flash": "^2.0",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "^5.4",
        "propaganistas/laravel-fakeid": "^2.0",
        "spatie/laravel-pjax": "^1.3",
        "zizaco/entrust": "dev-master"
    },
```

2. config\app.php

```
        Propaganistas\LaravelFakeId\FakeIdServiceProvider::class,
```
3. Ran 
```
php artisan fakeid:setup
```
and the 3 values have been added to the .env file

4. routes.php

```
Route::fakeIdModel('customers', 'App\Models\Customer');

    // Customers
    Route::get('customers',['as'=>'customers.index','uses'=>'CustomersController@index','middleware' => ['permission:customer-view|customer-create|customer-edit|customer-delete']]);
    Route::get('customers/create',['as'=>'customers.create','uses'=>'CustomersController@create','middleware' => ['permission:customer-create']]);
    Route::post('customers/create',['as'=>'customers.store','uses'=>'CustomersController@store','middleware' => ['permission:customer-create']]);
    Route::get('customers/{id}',['as'=>'customers.show','uses'=>'CustomersController@show','middleware' => ['permission:customer-view']]);
    Route::get('customers/{id}/edit',['as'=>'customers.edit','uses'=>'CustomersController@edit','middleware' => ['permission:customer-edit']]);
    Route::patch('customers/{id}',['as'=>'customers.update','uses'=>'CustomersController@update','middleware' => ['permission:customer-edit']]);
    Route::delete('customers/{id}',['as'=>'customers.destroy','uses'=>'CustomersController@destroy','middleware' => ['permission:customer-delete']]);
```

5. Model
```

use Propaganistas\LaravelFakeId\FakeIdTrait;

class Customer extends Model
{
    // Sortable trait adds Sortable scope to the model so we can use it with paginate
    use Sortable;
    // FakeId obfuscation
    use FakeIdTrait;
...
```

**Comment by Propaganistas** [comment]
Just as with Laravel's built-in `Route::model()`, you need to use the string provided as the first parameter in `Route::fakeIdModel()` as the id placeholder.

```php
Route::fakeIdModel('placeholder', 'App\Models\Customer');
Route::get('customers/{placeholder}', ....);

// So in your case you'd need
Route::fakeIdModel('customers', 'App\Models\Customer');
Route::get('customers/{customers}', .....);
// OR
Route::fakeIdModel('id', 'App\Models\Customer');
Route::get('customers/{id}', .....);
// OR
Route::fakeIdModel('customerId', 'App\Models\Customer');
Route::get('customers/{customerId}', .....);
```

I'd go with the last option.

**Comment by chandank** [comment]
I went with the last option but guess I'm still doing something wrong. The values in the index view still show up with the integer id and if I click to 'show' I get the following error:

> FatalErrorException in Optimus.php line 94:
> Call to undefined function Jenssegers\Optimus\gmp_intval()

**Comment by Propaganistas** [comment]
Well, I don't know anything about the contents of your index view, but you should be constructing URLs as follows:

```
// $customer is a Customer object
route('customers.show', ['customer' => $customer']);
```

This way you specify that the `{customer}` placeholder should be replaced with the `$customer` object. The trait will then tell Laravel to extract an obfuscated value for inclusion in the route.

The error you're experiencing is because your PHP installation doesn't have the `php_gmp` extension included, which is necessary in case of 32-bit servers (see https://github.com/jenssegers/optimus#installation)

**Comment by chandank** [comment]
FWIW, I enabled the php_gmp extension but somehow couldn't get it working. I've now switched to a different package using Hashids with route model binding in place and it worked like a charm. Thanks anyways.
