### ISSUE TITLE
How call the route() helper for obfuscated ids

### ISSUE THREAD

**Issue by Matienzo** [Propaganistas/Laravel-FakeId#15]
I want to use route() laravel helper to generate routes like "mymodel/{obfuscated_id}" but i get the old route "mymodel/autonumeric_id".
I have all installed exactly like the docs. 
it is possible to use route() helper for fakeids?

thank you

**Comment by Propaganistas** [comment]
Yes. You might have missed something because it should just work.

```php

use Illuminate\Database\Eloquent\Model;
use Propaganistas\LaravelFakeId\FakeIdTrait;

class MyModel extends Model {
  use FakeIdTrait;
}
```

```php
Route::fakeIdModel('mymodel', 'App\MyModel');
Route::get('model/{mymodel}', ....)->name('model_route');
```

```php
route('model_route', ['mymodel' => App\MyModel::find(1)]);
// Outputs example.org/model/{obfuscated_id}
```

**Comment by Matienzo** [comment]
Thanks,  I was calling the route incorrectly.
`route('model_route', model_id) `
but the correct way is 
`route('model_route', model_instance) `
