### ISSUE TITLE
Not defined fakeModelID uses optimus!

### ISSUE THREAD

**Issue by meNESS** [Propaganistas/Laravel-FakeId#16]
```php
Route::group(['prefix' => 'users'], function () {

    Route::group(['prefix' => '{user}'], function () {

        Route::group(['middleware' => 'auth'], function () {

            Route::delete('/', 'UserController@close')->middleware('can:close,user');
    });
    Route::get('/{username}', 'UserController@viewByUsername');
});
```

```php
Route::pattern('username', '[a-z0-9._]+');

Route::fakeIdModel('user', User::class);
```

The problem here is calling `users/{username}` returns 500 because it tries to decode the username using Optimus but I defined `username` as a pattern not a fake model ID! how can I fix this?

**Comment by Propaganistas** [comment]
If I'm not mistaken this scenario will also not work when using Laravel's default `Route::model()` functionality.

The problem here lies in the fact that there are two 'wildcard' route segments on the same level, namely `users/{user}` and `users/{username}`. Only the first one defined will take effect.

**Comment by meNESS** [comment]
@Propaganistas I first thought Laravel uses patterns instead of exact model names, so I changed the username pattern name to something else but nothing worked. I also tested `Route::model()` and you're right about it's not working. I also removed the route from the parent group but nothing worked. I think Laravel tries to figure out what the model is, but the model uses ID as its key not the username, so how should I tell Laravel don't try dear Laravel for this route?

**Comment by meNESS** [comment]
@Propaganistas I found the problem and it's related to Laravel! I don't know why, but Laravel cares about the order of defining routes. defining the `GET` route before the group makes everything work. Do you know why?

**Comment by Propaganistas** [comment]
See my previous answer:
> The problem here lies in the fact that there are two 'wildcard' route segments on the same level, namely `users/{user}` and `users/{username}`. Only the first one defined will take effect.

There are lots of related questions on StackOverflow about this topic, all talking about the same "issue", e.g. https://stackoverflow.com/questions/33212026/laravel-routes-ordering
