### ISSUE TITLE
Usage with dingo/api

### ISSUE THREAD

**Issue by nicolas-t** [Propaganistas/Laravel-FakeId#17]
Hello,

I'd like to use FakeId with [dingo/api](https://github.com/dingo/api).

but my routes are called this way (simplified version): 
```php
// routes.php

Route::fakeIdModel('userId', 'App\User');

$api->version('v1', [], function ($api) {
    $api->get(
        'users/{userId}',
        'App\Api\Controllers\UserController@show'
    );
    //  ...
});
```

In my controller methods `$userId` is still obfuscated.

I think this is because dingo uses it's own router instead of the native laravel router.
More information here :  
https://github.com/dingo/api/wiki/Creating-API-Endpoints

Do you think I can make `fakeId` work with dingo ? 

Thanks !

**Comment by Propaganistas** [comment]
According to [this line](https://github.com/dingo/api/blob/a8520136054d416b9e3f8f63779e4552c4ebccaa/src/Provider/LaravelServiceProvider.php#L60) `dingo/api` should re-implement previously set route bindings. So I'm unsure why it wouldn't work.

**Comment by nicolas-t** [comment]
Oh, okay.

in the meantime I chose to use a very basic route middleware :  
```php
<?php

namespace App\Http\Middleware;

use Closure;
use Jenssegers\Optimus\Optimus;

class UnobfuscateRouteParameters
{
    protected $optimus;

    public function __construct(Optimus $optimus)
    {
        $this->optimus = $optimus;
    }

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $params = [
            'userId'
        ];

        foreach ($request->route()->parameters() as $key => $value) {
            if (!in_array($key, $params)) { continue; }
            
            try {
                $request->route()->setParameter($key,  $this->optimus->decode($value));
            } catch (\InvalidArgumentException $e) {
                throw config('app.debug') ? $e : new NotFoundHttpException;
            }
        }

        return $next($request);
    }
}

```
