### ISSUE TITLE
fakeid:setup command has no handle method

### ISSUE THREAD

**Issue by sebastiaanluca** [Propaganistas/Laravel-FakeId#18]
Just wanted to give you a heads-up for the 5.5 release.

When running

```shell
php artisan fakeid:setup
```

I get

```
[ReflectionException]
Method Propaganistas\LaravelFakeId\Commands\FakeIdSetupCommand::handle() does not exist
```

The `fire` method in commands is deprecated and has been replaced by `handle`.

**Comment by Propaganistas** [comment]
Thanks for the notification! I've rolled a new release: https://github.com/Propaganistas/Laravel-FakeId/releases/tag/2.0.7

**Comment by sebastiaanluca** [comment]
Awesome, thanks!
