### ISSUE TITLE
Trait 'Propaganistas\LaravalFakeId\FakeIdTrait' not found

### ISSUE THREAD

**Issue by javaftper** [Propaganistas/Laravel-FakeId#2]
Thanks for releasing this package.

It's a great piece of functionality from reading the code.

Unfortunately I cannot get it to work from the install instructions because of a basic error which I imagine is something that is easy to resolve.

I have followed your install/setup instructions and then updated the following files-

routes.php
`Route::model('orange', 'App\Orange');
Route::resource('orange', 'OrangeController');`

Orange.php
`
namespace App;

use Illuminate\Database\Eloquent\Model;
use Propaganistas\LaravalFakeId\FakeIdTrait;
class Orange extends Model
{
	
  use FakeIdTrait;

    protected $fillable = ['orange_name'];
}
`
When I load- http://localhost:8000/orange/3

I received the following -
`FatalErrorException in Orange.php line 10:
Trait 'Propaganistas\LaravalFakeId\FakeIdTrait' not found`

I don't think I've used traits in vendor packages before- normally I define in the App folder.  Is there some kind of config etc I need to set up to enable this to work?

I'm using laravel 5.2 and the latest version of your package.

**Comment by Propaganistas** [comment]
It seems the package is not loaded by composer. Did you properly install it using composer?
Please try `composer require propaganistas/laravel-fakeid`

**Comment by javaftper** [comment]
Yep, installed and config'd successfully.

Could it be related to psr-4 for autoloading?

This is my composer.json -
`
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
	"propaganistas/laravel-fakeid": "^1.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
`

**Comment by javaftper** [comment]
Closing. Created PR. Typo in readme.

**Comment by Propaganistas** [comment]
Glad you found the causing issue. Thanks.
