### ISSUE TITLE
Does it work with relationships?

### ISSUE THREAD

**Issue by robfrancken** [Propaganistas/Laravel-FakeId#21]
Until now the only way I have been able to get it to work on relationships is by adding a slug field in the DB, and then using getRouteKeyName(). Is there another way?

**Comment by Propaganistas** [comment]
I'm having a hard time seeing the bigger picture. Please describe in detail what you're trying to achieve, provide some code snippets, ...

**Comment by robfrancken** [comment]
My bad, I was using an accessor to override the ID attribute so that I didn't have to modify my controllers or views, but obviously Eloquent is no longer able to resolve relationships as a result.
```
    public function getIdAttribute($value) {
        return App::make('fakeid')->encode($value);
    }
```
I guess I should rephrase my question. Is there anyway of using the Optimus library in conjunction with Laravel-FakeId without having to do things like `$optimus->encode(1)`, or `FakeId::encode(1)` everywhere it is needed?

**Comment by robfrancken** [comment]
Because I'm using hashed slugs in so many places, I just ended up sharing an instance of Fakeid with my views via a view composer :)

**Comment by Propaganistas** [comment]
There's actually no need to question if FakeId and Optimus can be used in conjunction, as FakeId is merely a wrapper of Optimus in some Laravel-specific areas. Optimus functionality is 100% preserved and just used by FakeId where needed.

So yes, if you want to use Optimus as is elsewhere, just pull in the FakeId/Optimus instance.
