### ISSUE TITLE
How to make it work with soft delete?

### ISSUE THREAD

**Issue by azeos** [Propaganistas/Laravel-FakeId#22]
I have the package working correctly. But one of my models use [soft delete](https://laravel.com/docs/5.4/eloquent#soft-deleting). As soon as I soft delete a record, I can't access it any more.

> NotFoundHttpException
> in FakeIdServiceProvider.php (line 90)

RouteServiceProvider.php
`Route::fakeIdModel('project', \App\Project::class);`

I see that `Route::fakeIdModel()` has a third parameter for a callback, maybe that's the place to include the `withTrashed()` logic, but I don't know how.

I'm using Laravel 5.4.
Any information will be appreciated.

Thanks,
azeos.

**Comment by Propaganistas** [comment]
Similar to the built-in `model` binding, there's no clean way to include soft deleted models.

As you suggested yourself you could use the callback parameter to perform another query and do something like this:

```php
use App;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

Route::fakeIdModel('project', \App\Project::class, function($project) {
    $instance = App::make(\App\Project::class);

    // $project is the route parameter value and is already decoded!
    if ($model = $instance->withTrashed()->where($instance->getRouteKeyName(), $project)->first()) {
        return $model;
    }

    throw new NotFoundHttpException;
});
```

(code written off the top of my head; not tested)

**Comment by azeos** [comment]
Excellent! I ended with this code:

```php
Route::fakeIdModel('project', \App\Project::class, function ($id) {
    return \App\Project::withTrashed()->findOrFail($id);
});
```

If I'm not missing something, it should be pretty much the same thing.

Thanks, I really appreciate your help and your quick response.
