### ISSUE TITLE
By throwing an Exception in registerRouterMacro a user defined callback can not be run

### ISSUE THREAD

**Issue by Gnative** [Propaganistas/Laravel-FakeId#24]
https://github.com/Propaganistas/Laravel-FakeId/blob/9b69eb1a3ddee30148587ff4e2811fbb4b3647ff/src/FakeIdServiceProvider.php#L75

**Comment by Propaganistas** [comment]
I've created a new release (4.0.0 - breaking changes) that incorporates more up to date logic and also resolves this issue indirectly.
