### ISSUE TITLE
propaganistas/laravel-cache-keywords DELETED???

### ISSUE THREAD

**Issue by unitedworx** [Propaganistas/Laravel-FakeId#33]
sorry for writing this here

propaganistas/laravel-cache-keywords IS DELETED???

I was using this in many projects nd now ALL are broken!

can you please bring this back? or at least send me the zip to add on my account?

**Comment by unitedworx** [comment]
please restore the repo

https://help.github.com/en/github/administering-a-repository/restoring-a-deleted-repository

**Comment by Propaganistas** [comment]
The package has been marked as abandoned on Packagist for over a year. From that point on all composer installs and updates showed clear warnings. There was ample time to move on and update any applications.

I see you’ve been able to create a repo yourself, so I’m closing this.
