### ISSUE TITLE
Generating same id for all models

### ISSUE THREAD

**Issue by RVP04** [Propaganistas/Laravel-FakeId#35]
I have used the hashids in my file. 

`\App\Role::class => [
            'salt' => Str::uuid(),
            'length' => 10,
        ],
\App\User::class => [
            'salt' => \App\User::class . '7623e9b0009feff8e024a689d6ef59ce',
            'length' => 10,
        ],`
But same id is given for both models. Please help me

**Comment by Propaganistas** [comment]
I have absolutely no idea what you're talking about. I don't see any references to this package.

**Comment by RVP04** [comment]
Sir,
If user model first record I’d is 1 generating one id. 
Role Model first record I’d is 1 and generating same id of the user 

1st user Fakeid is 231231
1st role fakeid is same 231231

I have used different salt and different length. Please clarify sir

**Comment by Propaganistas** [comment]
Since you're talking abouts salts and lengths I suspect that you're using https://github.com/vinkla/laravel-hashids instead of this package. This package doesn't make use of salts.

Please redirect your question there.

**Comment by RVP04** [comment]
> Since you're talking abouts salts and lengths I suspect that you're using https://github.com/vinkla/laravel-hashids instead of this package. This package doesn't make use of salts.
> 
> 
> 
> Please redirect your question there.

But this is your package. Your package is using the hashids and generating the same id. 

Please help me

**Comment by Propaganistas** [comment]
The code you're showing has nothing to do with this package. This package doesn't even have "salts".

Yes, both packages implement some kind of logic to achieve obfuscated ids, but they do it in a completely different way.
* "Hashids" using salts = https://github.com/vinkla/laravel-hashids
* Fake ids using Optimus = this package

You're constantly referring to "hashids" and "salts", so you're not using this package.

**Comment by RVP04** [comment]
Ok I will check and get back to you
