### ISSUE TITLE
Route Model Binding(slug)

### ISSUE THREAD

**Issue by boranbar** [Propaganistas/Laravel-FakeId#38]
Hello,

As you already know, with Laravel 7.x we can override routekeyname directly inside routes.

For example;
//web.php
Route::get('demos/{demo:slug}','DemoController@slug')->name('demo.slug');
//Controller
public function slug(Demo $demo)
    {
        dd($demo);
    }

when i try to go url with slug it gives me 404 page. So is there anyway to use route model binding for slugs?

**Comment by Propaganistas** [comment]
I don't understand what you're trying to do.
Fake id obfuscation is all about hiding an internal id to the outside. A slug is just another alternative to using fake ids.
