### ISSUE TITLE
Select 2 box not showing the fakeid

### ISSUE THREAD

**Issue by RVP04** [Propaganistas/Laravel-FakeId#39]
Sir, 

I am using your fakeid package. In the select box it is showing the primary key and not the fake id. 

RouteServiceProvider.php
Route::model('country',Country::class);

I getting all the country from the model and showing in the blade using select or select2. It is not showing the fakeid. Please help em

**Comment by Propaganistas** [comment]
Use `getRouteKey()` instead of `getKey()` when populating your select options.
