### ISSUE TITLE
Optimus::__construct(): Argument #1 ($prime) must be of type int, null given, called in FakeIdServiceProvider.php:46

### ISSUE THREAD

**Issue by masroore** [Propaganistas/Laravel-FakeId#42]
The  following exception is generated by the barryvdh/laravel-ide-helper `php artisan ide-helper:generate` command:

    TypeError
  
    Jenssegers\Optimus\Optimus::__construct(): Argument #1 ($prime) must be of type int, null given, called in ...\vendor\propaganistas\laravel-fakeid\src\FakeIdServiceProvider.php on line 46
  
    at ...\vendor\jenssegers\optimus\src\Optimus.php:49
       45▕      * @var int
       46▕      */
       47▕     private $max;
       48▕
    ➜  49▕     public function __construct(int $prime, int $inverse, int $xor = 0, int $size = self::DEFAULT_SIZE)
       50▕     {
       51▕         $this->prime = $prime;
       52▕         $this->inverse = $inverse;
       53▕         $this->xor = $xor;
  
    1   ...\vendor\propaganistas\laravel-fakeid\src\FakeIdServiceProvider.php:46
        Jenssegers\Optimus\Optimus::__construct()
  
    2   ...\vendor\laravel\framework\src\Illuminate\Container\Container.php:829
        Propaganistas\LaravelFakeId\FakeIdServiceProvider::Propaganistas\LaravelFakeId\{closure}()

**Comment by Propaganistas** [comment]
As a default prime value is provided, this can only happen if you have **overridden** FakeId's config:
https://github.com/Propaganistas/Laravel-FakeId/blob/0da99e347ec91061abbb458654e54ac944722937/config/config.php#L19

or if your **ENV variable is unconfigured**:
```FAKEID_PRIME=```

**Comment by masroore** [comment]
The overridden config values are okay and the system works as expected.

config/fakeid.php:
```
  <?php

  return [

      'prime'   => env('FAKEID_PRIME', 961748927),
      'inverse' => env('FAKEID_INVERSE', 1430310975),
      'random'  => env('FAKEID_RANDOM', 620464665),

  ]; 
```
.env:
```
  FAKEID_PRIME=2079660683
  FAKEID_INVERSE=2030501155
  FAKEID_RANDOM=1328123201
```
It's only when I run `php artisan ide-helper:generate` the null parameter on `Optimus::__construct()` exception is generated. I guess this particular error has more to do with barryvdh/laravel-ide-helper than your repository, for some reason it doesn't initialize the env/cfg variables when the ide-helper:generate command is run.

FYI, I am on Windows 10 x64, PHP 8 .0.3 x64 and Laravel 8.12

**Comment by masroore** [comment]
FIXED: my bad. this error happened due to obsolete config:cache. after invalidation, it's working as expected.
