### ISSUE TITLE
Soft deletes

### ISSUE THREAD

**Issue by dotsoftwarenl** [Propaganistas/Laravel-FakeId#50]
Hi, 

We are currently starting to implement Laravel-FakeId. We are using Laravel soft deletes, when a user is soft deleted the user can still be visited via this block of code:

`User.php`
```
    /**
     * Resolve the path of the deleted user, the user can still access this resource.
     *
     * @var int
     */
    public function resolveRouteBinding($value, $field = null)
    {
        return in_array(SoftDeletes::class, class_uses($this))
            ? $this->where($this->getRouteKeyName(), $value)->withTrashed()->first()
            : parent::resolveRouteBinding($value);
    }
```

But due to the implementation of Laravel-FakeId, this does not work anymore. I did already review the previous two issues posted on this repository, but it seems that those solutions don't work anymore. This is the block of code that I was using:

`RouteServiceProvider.php`
```
        Route::model('User', \App\Models\User::class, function ($id) {
            return \App\Models\User::withTrashed()->findOrFail(
                App::make('fakeid')->decode((int) $id)
            );
        });
```

Is there a way to still view the deleted resource?

**Comment by Propaganistas** [comment]
How about just this?

https://laravel.com/docs/10.x/routing#implicit-soft-deleted-models

**Comment by Propaganistas** [comment]
Explicit model bindings completely omit a model's route resolution logic and hence bypass the route resolution of the package. `Route::get(...)->withTrashed()` only works for implicit bindings, so it won't help us either.

This should work (as proven by a [test](https://github.com/Propaganistas/Laravel-FakeId/blob/7987f3bb0621eb1961a4b3ebc76f459c3c93239d/tests/FakeIdTest.php#L213-L239)):

```php
Route::model('User', User::class, function ($value) {
    return (new User)->resolveRouteBindingQuery(User::withTrashed(), $value)->firstOrFail();
});
```

This way you leave the decoding part buried inside the package.

**Comment by dotsoftwarenl** [comment]
Hi @Propaganistas,

I changed the `Route::model('User', User::class, function ($value) {` to `Route::model('user', User::class, function ($value) {` and it worked like a charm.

Thanks a lot for maintaining this package so frequently!
